//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ztznpms.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("id")]
        public string id {
            get {
                return ((string)(this["id"]));
            }
            set {
                this["id"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("项目名称")]
        public string 项目名称 {
            get {
                return ((string)(this["项目名称"]));
            }
            set {
                this["项目名称"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("工作令号")]
        public string 工作令号 {
            get {
                return ((string)(this["工作令号"]));
            }
            set {
                this["工作令号"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("设备名称")]
        public string 设备名称 {
            get {
                return ((string)(this["设备名称"]));
            }
            set {
                this["设备名称"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("编码")]
        public string 编码 {
            get {
                return ((string)(this["编码"]));
            }
            set {
                this["编码"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("图号")]
        public string 图号 {
            get {
                return ((string)(this["图号"]));
            }
            set {
                this["图号"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("名称")]
        public string 名称 {
            get {
                return ((string)(this["名称"]));
            }
            set {
                this["名称"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("设备编号")]
        public string 设备编号 {
            get {
                return ((string)(this["设备编号"]));
            }
            set {
                this["设备编号"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("数量")]
        public string 数量 {
            get {
                return ((string)(this["数量"]));
            }
            set {
                this["数量"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("工序名称")]
        public string 工序名称 {
            get {
                return ((string)(this["工序名称"]));
            }
            set {
                this["工序名称"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("价格")]
        public string 价格 {
            get {
                return ((string)(this["价格"]));
            }
            set {
                this["价格"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("工序顺序")]
        public string 工序顺序 {
            get {
                return ((string)(this["工序顺序"]));
            }
            set {
                this["工序顺序"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("工序内容")]
        public string 工序内容 {
            get {
                return ((string)(this["工序内容"]));
            }
            set {
                this["工序内容"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("负责人")]
        public string 负责人 {
            get {
                return ((string)(this["负责人"]));
            }
            set {
                this["负责人"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("实际操作人")]
        public string 实际操作人 {
            get {
                return ((string)(this["实际操作人"]));
            }
            set {
                this["实际操作人"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("开始时间")]
        public string 开始时间 {
            get {
                return ((string)(this["开始时间"]));
            }
            set {
                this["开始时间"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("结束时间")]
        public string 结束时间 {
            get {
                return ((string)(this["结束时间"]));
            }
            set {
                this["结束时间"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("工序外协开始")]
        public string 工序外协开始 {
            get {
                return ((string)(this["工序外协开始"]));
            }
            set {
                this["工序外协开始"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("工序外协结束")]
        public string 工序外协结束 {
            get {
                return ((string)(this["工序外协结束"]));
            }
            set {
                this["工序外协结束"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("二维码")]
        public string 二维码 {
            get {
                return ((string)(this["二维码"]));
            }
            set {
                this["二维码"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("标记")]
        public string 标记 {
            get {
                return ((string)(this["标记"]));
            }
            set {
                this["标记"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.15.1.252;Initial Catalog=db_ShengChanBu;Persist Security Info=True" +
            ";User ID=sa")]
        public string db_ShengChanBuConnectionString {
            get {
                return ((string)(this["db_ShengChanBuConnectionString"]));
            }
        }
    }
}
